// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_gamma_Rcpp
NumericVector calc_gamma_Rcpp(NumericMatrix x, IntegerVector ix, IntegerVector iy, int bn);
RcppExport SEXP _geiprs_calc_gamma_Rcpp(SEXP xSEXP, SEXP ixSEXP, SEXP iySEXP, SEXP bnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iy(iySEXP);
    Rcpp::traits::input_parameter< int >::type bn(bnSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_gamma_Rcpp(x, ix, iy, bn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geiprs_calc_gamma_Rcpp", (DL_FUNC) &_geiprs_calc_gamma_Rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_geiprs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
