# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_gamma_Rcpp <- function(x, ix, iy, bn) {
    .Call('_geiprs_calc_gamma_Rcpp', PACKAGE = 'geiprs', x, ix, iy, bn)
}

